// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RecordingStudio.BookingEngine.Infrastructure.Data;

#nullable disable

namespace RecordingStudio.BookingEngine.Infrastructure.Migrations
{
    [DbContext(typeof(BookingEngineDbContext))]
    [Migration("20260715220041_SeedReferenceData")]
    partial class SeedReferenceData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("RecordingStudio.BookingEngine.Core.Entities.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DurationHours")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ServiceTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StudioId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ServiceTypeId");

                    b.HasIndex("StudioId");

                    b.HasIndex("UserId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("RecordingStudio.BookingEngine.Core.Entities.Facility", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Facilities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Microphone"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Mixing Console"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Vocal Booth"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Grand Piano"
                        });
                });

            modelBuilder.Entity("RecordingStudio.BookingEngine.Core.Entities.ServiceType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ServiceTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Standard recording session",
                            Name = "Recording Session"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Mixing an existing recording",
                            Name = "Mixing"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Recording session with grand piano",
                            Name = "Piano Recording"
                        });
                });

            modelBuilder.Entity("RecordingStudio.BookingEngine.Core.Entities.ServiceTypeRequiredFacility", b =>
                {
                    b.Property<int>("ServiceTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FacilityId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ServiceTypeId", "FacilityId");

                    b.HasIndex("FacilityId");

                    b.ToTable("ServiceTypeRequiredFacilities");

                    b.HasData(
                        new
                        {
                            ServiceTypeId = 1,
                            FacilityId = 1
                        },
                        new
                        {
                            ServiceTypeId = 1,
                            FacilityId = 2
                        },
                        new
                        {
                            ServiceTypeId = 2,
                            FacilityId = 2
                        },
                        new
                        {
                            ServiceTypeId = 3,
                            FacilityId = 1
                        },
                        new
                        {
                            ServiceTypeId = 3,
                            FacilityId = 2
                        },
                        new
                        {
                            ServiceTypeId = 3,
                            FacilityId = 4
                        });
                });

            modelBuilder.Entity("RecordingStudio.BookingEngine.Core.Entities.Studio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sector")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Studios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Studio A",
                            Sector = "Downtown"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Studio B",
                            Sector = "Uptown"
                        });
                });

            modelBuilder.Entity("RecordingStudio.BookingEngine.Core.Entities.StudioClosure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("StudioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StudioId");

                    b.ToTable("StudioClosures");
                });

            modelBuilder.Entity("RecordingStudio.BookingEngine.Core.Entities.StudioFacility", b =>
                {
                    b.Property<int>("StudioId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FacilityId")
                        .HasColumnType("INTEGER");

                    b.HasKey("StudioId", "FacilityId");

                    b.HasIndex("FacilityId");

                    b.ToTable("StudioFacilities");

                    b.HasData(
                        new
                        {
                            StudioId = 1,
                            FacilityId = 1
                        },
                        new
                        {
                            StudioId = 1,
                            FacilityId = 2
                        },
                        new
                        {
                            StudioId = 1,
                            FacilityId = 3
                        },
                        new
                        {
                            StudioId = 2,
                            FacilityId = 1
                        },
                        new
                        {
                            StudioId = 2,
                            FacilityId = 2
                        },
                        new
                        {
                            StudioId = 2,
                            FacilityId = 4
                        });
                });

            modelBuilder.Entity("RecordingStudio.BookingEngine.Core.Entities.StudioServiceExclusion", b =>
                {
                    b.Property<int>("StudioId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ServiceTypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("StudioId", "ServiceTypeId");

                    b.HasIndex("ServiceTypeId");

                    b.ToTable("StudioServiceExclusions");

                    b.HasData(
                        new
                        {
                            StudioId = 1,
                            ServiceTypeId = 2
                        });
                });

            modelBuilder.Entity("RecordingStudio.BookingEngine.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "client@example.com",
                            Name = "Test Client"
                        });
                });

            modelBuilder.Entity("RecordingStudio.BookingEngine.Core.Entities.Booking", b =>
                {
                    b.HasOne("RecordingStudio.BookingEngine.Core.Entities.ServiceType", "ServiceType")
                        .WithMany("Bookings")
                        .HasForeignKey("ServiceTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecordingStudio.BookingEngine.Core.Entities.Studio", "Studio")
                        .WithMany("Bookings")
                        .HasForeignKey("StudioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecordingStudio.BookingEngine.Core.Entities.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceType");

                    b.Navigation("Studio");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RecordingStudio.BookingEngine.Core.Entities.ServiceTypeRequiredFacility", b =>
                {
                    b.HasOne("RecordingStudio.BookingEngine.Core.Entities.Facility", "Facility")
                        .WithMany("ServiceTypeRequiredFacilities")
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecordingStudio.BookingEngine.Core.Entities.ServiceType", "ServiceType")
                        .WithMany("ServiceTypeRequiredFacility")
                        .HasForeignKey("ServiceTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Facility");

                    b.Navigation("ServiceType");
                });

            modelBuilder.Entity("RecordingStudio.BookingEngine.Core.Entities.StudioClosure", b =>
                {
                    b.HasOne("RecordingStudio.BookingEngine.Core.Entities.Studio", "Studio")
                        .WithMany("StudioClosures")
                        .HasForeignKey("StudioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Studio");
                });

            modelBuilder.Entity("RecordingStudio.BookingEngine.Core.Entities.StudioFacility", b =>
                {
                    b.HasOne("RecordingStudio.BookingEngine.Core.Entities.Facility", "Facility")
                        .WithMany("StudioFacilities")
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecordingStudio.BookingEngine.Core.Entities.Studio", "Studio")
                        .WithMany("StudioFacilities")
                        .HasForeignKey("StudioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Facility");

                    b.Navigation("Studio");
                });

            modelBuilder.Entity("RecordingStudio.BookingEngine.Core.Entities.StudioServiceExclusion", b =>
                {
                    b.HasOne("RecordingStudio.BookingEngine.Core.Entities.ServiceType", "ServiceType")
                        .WithMany("StudioServiceExclusions")
                        .HasForeignKey("ServiceTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecordingStudio.BookingEngine.Core.Entities.Studio", "Studio")
                        .WithMany("StudioServiceExclusions")
                        .HasForeignKey("StudioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceType");

                    b.Navigation("Studio");
                });

            modelBuilder.Entity("RecordingStudio.BookingEngine.Core.Entities.Facility", b =>
                {
                    b.Navigation("ServiceTypeRequiredFacilities");

                    b.Navigation("StudioFacilities");
                });

            modelBuilder.Entity("RecordingStudio.BookingEngine.Core.Entities.ServiceType", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("ServiceTypeRequiredFacility");

                    b.Navigation("StudioServiceExclusions");
                });

            modelBuilder.Entity("RecordingStudio.BookingEngine.Core.Entities.Studio", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("StudioClosures");

                    b.Navigation("StudioFacilities");

                    b.Navigation("StudioServiceExclusions");
                });

            modelBuilder.Entity("RecordingStudio.BookingEngine.Core.Entities.User", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
